const KEY="rr25_ritual_v1";
const NOTEKEY="rr25_notiz_v1";
let BOOKTEXT="";
const R=[
{id:"dank",t:"Tägliches Dankesritual",s:"Gesundheit · Liebe · Geld · Schutz",tag:"Alltag",steps:[["Ankommen","Füße. Atem. Ich bin der Spieler. Der Beobachter ist wach."],["Dank","Für jedes Thema dreimal: Danke für Gesundheit. Danke für Liebe. Danke für Geld und Versorgung. Danke für Schutz durch das Feld."],["Setzen","Ich bin gesund. Es ist so. Ich bin geliebt. Es ist so. Ich bin versorgt. Es ist so. Ich bin geschützt. Es ist so."],["Siegel","Optional Salz auf jede Kerze. Dies versiegelt und reinigt."],["Abschluss","Dreimal: Danke für alles. Die Arbeit ist dem Feld übergeben."]]},
{id:"stopp",t:"Schaden stoppen",s:"Angriff endet. Feld zu.",tag:"Schutz",need:["Name"],steps:[["Schutz zuerst","Ich bin in meiner Mitte. Mein Feld ist geschlossen. Nichts Fremdes hat Zutritt."],["Lage","[Name] will schaden. Ich halte das hier auf. Ohne Hass. Ohne mich zu verlieren."],["Absicht","Jeder Angriff von [Name] auf mich, mein Haus und meine Leute stoppt jetzt. Die Bahn ist zu."],["369","3× Der Schaden stoppt. 6× Der Zugriff fällt ab. 9× Ich bin frei und geschützt. Es ist so."],["Grenze","Kein Nachsetzen. Kein Zerlegen. Nur Stopp und Distanz."],["Rückkehr","Ich bin nicht [Name]. Ich kehre vollständig zurück. Meine Energie gehört mir."]]},
{id:"schutz",t:"Schutz selbst",s:"Feld schliessen",tag:"Schutz",steps:[["Ankommen","Ich bin der Spieler. Der Beobachter ist wach. Ich handle aus klarer Mitte."],["Rahmen","Ich öffne diesen Raum nur für Schutz. Nur das Stimmige und Reine darf hier sein."],["Absicht","Ich schütze mich jetzt vollständig. Mein Feld ist geschlossen, klar und stabil. Jede fremde Energie prallt ab oder geht in die Erde. Meine Energie gehört allein mir."],["369","3× Mein Schutz ist aktiv und stark. 6× Alles Fremde prallt ab und findet keinen Halt. 9× Ich bin klar, geschützt und bei mir."],["Abschluss","Körpergrenze spüren. Der Schutz ist gesetzt und versiegelt."]]},
{id:"schutz2",t:"Schutz für eine andere Person",s:"Vor Arbeit oder Tag",tag:"Schutz",need:["Name"],steps:[["Mitte","Ich bin in meiner Mitte. Ich richte mich auf [Name] aus, ohne mich zu verlieren."],["Absicht","Das Feld von [Name] wird klar und geschützt. Die Energie bleibt bei [Name]. Alles Ziehende prallt ab."],["369","3× Die Energie von [Name] ist geschützt. 6× Ihr Feld bleibt klar und geschlossen. 9× [Name] ist in der Kraft. Es ist so."],["Rückkehr","Ich bin nicht [Name]. Ich kehre vollständig in mich zurück. Meine Energie gehört mir."]]},
{id:"heil",t:"Heilung",s:"Ergänzung zur Medizin",tag:"Energie",need:["Name"],steps:[["Rahmen","Ich öffne nur für reine und stimmige Heilung. Arzt bleibt parallel."],["Absicht","Die Wunde von [Name] findet jetzt natürliche, vollständige Heilung. Alles, was die Heilung behindert, löst sich."],["369","3× Die Wunde von [Name] heilt vollständig. 6× Alles Störende löst sich. 9× Die Heilung ist im Gange."],["Rückkehr","Ich bin nicht [Name]. Zum höchsten Wohl. Ich kehre vollständig zurück."]]},
{id:"trenn",t:"Trennung — selbst",s:"Nur der Faden",tag:"Trennung",need:["Name"],steps:[["Rahmen","Ich öffne nur für klare Trennung. Ich bleibe in meiner Mitte."],["Absicht","Die Verbindung zwischen mir und [Name] löst sich. Alle unstimmigen Fäden werden getrennt. Ich lasse frei und werde frei."],["Grenze","Nur der Faden. Kein Urteil. Kein Nachsetzen."],["369","3× Die Verbindung löst sich. 6× Fäden fallen ab und kehren zum Ursprung. 9× Die Trennung ist vollzogen."],["Rückkehr","Ich bin nicht [Name]. Ich kehre vollständig in mich zurück. Meine Energie gehört mir."]]},
{id:"trenn2",t:"Trennung zweier anderer",s:"Nur der Faden",tag:"Trennung",need:["A","B"],steps:[["Position","Ich bleibe in meiner Mitte. Ihre Wege gehören ihnen. Den Faden zwischen ihnen wahrnehmen, nicht den zu dir."],["Absicht","Die unstimmige Verbindung zwischen [A] und [B] löst sich. Jeder gehört wieder sich selbst. Ohne Hass, ohne Schaden."],["369","3× Die Verbindung zwischen [A] und [B] löst sich. 6× Die Fäden fallen ab. 9× Sie sind voneinander frei."],["Rückkehr","Ich bin nicht [A]. Ich bin nicht [B]. Ich kehre vollständig zurück."]]},
{id:"wesen",t:"Nur wenn nötig — Wesenheit",s:"Fragen, begrenzen, entlassen",tag:"Feld",need:["A","B"],steps:[["Prüfen","Nur wenn der einfache Faden nicht reicht. Sonst zurück zur Lösung ohne Wesenheit."],["Schutz","Ich öffne nur für klare Hilfe. Unklares bleibt draußen. Ich behalte den Raum."],["Fragen","Wer bereit und geeignet ist, die Verbindung zwischen [A] und [B] zu lösen, möge sich zeigen."],["Auftrag","Nur Trennung. Kein unnötiger Schaden. Der Auftrag endet mit der Lösung."],["Entlassen","Danke. Wenn erfüllt, bist du frei. Verbindungen zu mir lösen sich. Kontakt beendet."],["Rückkehr","Ich bin nicht [A]. Ich bin nicht [B]. Ich kehre vollständig zurück. Meine Energie gehört mir."]]},
{id:"liebe",t:"Liebesritual",s:"Anziehung ohne Zwang",tag:"Liebe",need:["Name"],steps:[["Rahmen","Ich öffne nur für stimmige Liebe. Kein Festhalten. Kein Brechen des Willens."],["Absicht","Zwischen mir und [Name] darf sich stimmige Nähe zeigen. Wärme, Kontakt, Ehrlichkeit. Nur wenn es für beide wahr ist."],["369","3× Die Anziehung ist klar. 6× Der Weg öffnet sich leicht. 9× Liebe findet uns, wenn sie stimmig ist."],["Grenze","Kein Zwang. Kein Kleben. Jeder bleibt frei."],["Rückkehr","Ich bin nicht [Name]. Ich kehre vollständig in mich zurück."]]},
{id:"anz",t:"Anziehung und Kontakt",s:"Nur wenn stimmig",tag:"Liebe",need:["Name"],steps:[["Rahmen","Nur stimmiger Kontakt. Kein Festhalten."],["Absicht","[Name] fühlt die Anziehung. Kontakt geschieht leicht und natürlich. Nur wenn es für beide stimmig ist."],["369","3× Die Anziehung ist da. 6× Der Kontakt findet den Weg. 9× Es ist so."],["Rückkehr","Ich kehre in mich zurück. Die Arbeit ist übergeben."]]},
{id:"karma",t:"Karma-Ausgleich",s:"Nicht Rache",tag:"Energie",steps:[["Schutz","Erst das eigene Feld schliessen."],["Absicht","Was mir genommen oder aufgeladen wurde, kehrt in stimmiger Form zurück. Der Ausgleich geschieht ohne Hass. Die Last darf gehen."],["369","3× Der Ausgleich geschieht. 6× Die Energie kehrt rein zurück. 9× Es ist vollendet."],["Abschluss","Abgeben. Nicht nachkontrollieren."]]},
{id:"finst",t:"Finsternis",s:"Verstärken und versiegeln",tag:"Feld",steps:[["Rahmen","Ich öffne nur für klare Arbeit. Die Kraft darf lösen, klären und verstärken, was bereits im Feld ist."],["Absicht","Was nicht mehr stimmig ist, darf abfallen. Was gesetzt und wahr ist, wird gestärkt. Mein Feld bleibt klar."],["369","3× Altes löst sich. 6× Das Feld klärt und verstärkt. 9× Es ist gesetzt und vollendet."],["Abschluss","Die Arbeit wirkt. Ich danke und schliesse."]]},
{id:"ahn",t:"Ahnenkontakt",s:"Ehren und begrenzen",tag:"Feld",need:["Name"],steps:[["Rahmen","Nur für [Name], klar und stimmig. Last bleibt draußen."],["Einladung","[Name], wenn du bereit und willens bist, zeige dich. Ich möchte verstehen, nicht übernehmen."],["Grenze","Ich ehre dich und die Linie. Ich gehöre mir selbst. Ungesunde Muster lasse ich nicht in mein Leben."],["Schluss","Danke. Du kannst in Frieden gehen. Ich schliesse den Kontakt. Meine Energie gehört mir."]]},
{id:"fremd",t:"Fremde Wesenheit",s:"Kurz. Hartes Ende",tag:"Feld",steps:[["Rahmen","Nur klare, erkennbare Wesenheit ohne Täuschung. Ich behalte den Raum."],["Einladung","Wer bereit und in der Lage ist, sich klar zu zeigen, möge sich melden."],["Prüfen","Bleibt die eigene Mitte? Klar oder neblig? Druck oder Ruhe? Bei Unklarheit sofort schliessen."],["Ende","Der Kontakt ist beendet. Alle Verbindungen lösen sich. Du gehst und bleibst nicht. Der Raum gehört mir."]]},
{id:"zur",t:"Energie zurückholen",s:"Nach Kontakt",tag:"Energie",steps:[["Absicht","Alles, was von mir genommen wurde oder an mir hängt, kehrt jetzt rein und vollständig zu mir zurück. Fremde Energie löst sich und geht."],["Lage","Ich bin klar, ruhig und bei mir."],["Abschluss","Danach Wasser, Körper, Alltag."]]},
{id:"fil",t:"Filterübung",s:"Kein Auftrag",tag:"Feld",steps:[["Filter","Nur klare, stimmige Präsenz. Was drängt, bleibt draußen."],["Zeigen","Nur zeigen. Nicht fragen. Nicht anfreunden. Kein Auftrag."],["Schliessen","Kontakt beendet. Verbindungen lösen sich. Der Raum gehört mir."]]}
];
const $=(s,r=document)=>r.querySelector(s);
const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>Date.now().toString(36)+Math.random().toString(36).slice(2,6);
const now=()=>new Date().toLocaleString("de-CH");
const fill=(s,m)=>s.replaceAll("[Name]",m.Name||"[Name]").replaceAll("[A]",m.A||"[A]").replaceAll("[B]",m.B||"[B]");
const esc=s=>String(s||"").replace(/&/g,"&").replace(/</g,"<").replace(/>/g,">");
function load(){try{return Object.assign({log:[],planned:[]},JSON.parse(localStorage.getItem(KEY)||"{}"))}catch(e){return{log:[],planned:[]}}}
function save(d){localStorage.setItem(KEY,JSON.stringify(d))}
function loadNotes(){try{const x=JSON.parse(localStorage.getItem(NOTEKEY)||"[]");return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveNotes(a){localStorage.setItem(NOTEKEY,JSON.stringify(a))}
let cat="Alle",mem={},fromPlan=null;
function show(id){$$(".screen").forEach(s=>s.classList.toggle("on",s.id===id));$$("nav button").forEach(b=>b.classList.toggle("on",b.dataset.v===id||((id==="run"||id==="after"||id==="bye")&&b.dataset.v==="home")));if(id==="home")renderList();if(id==="geplant")paintPlan();if(id==="notiz")paintNotes();if(id==="log")paintLog();if(id==="buch")paintBuch();window.scrollTo(0,0)}
function stepsFor(r,mit){const b=r.steps.map(s=>s.slice());if(mit){const i=b.findIndex(s=>/Rückkehr|Abschluss|Ende|Schluss/.test(s[0]));const w=[["Wesenheit","Nur stimmig öffnen. Wer bereit ist, darf sich zeigen."],["Entlassen","Danke. Du gehst. Alle Verbindungen lösen sich."]];if(i>=0)b.splice(i,0,...w);else b.push(...w)}return b}
function openR(id,wer){const r=R.find(x=>x.id===id);if(!r)return;let i=0,mit=null,steps=[];mem={};if(wer){mem.Name=wer;const p=wer.split(/\s*·\s*/);mem.A=p[0]||wer;mem.B=p[1]||""}
const gate=()=>{$("#run").innerHTML=`<div class="hero"><p class="sub">${r.t}</p><h2>Wesenheit?</h2></div><div class="row"><button class="btn ghost" id="wOhne">Ohne</button><button class="btn primary" id="wMit">Mit</button></div><div class="row"><button class="btn ghost" id="wBack">Liste</button></div>`;$("#wOhne").onclick=()=>{mit=false;steps=stepsFor(r,false);i=0;draw()};$("#wMit").onclick=()=>{mit=true;steps=stepsFor(r,true);i=0;draw()};$("#wBack").onclick=()=>show("home")};
const draw=()=>{const [titel,text]=steps[i],last=i===steps.length-1;const names=(i===0?(r.need||[]):[]).map(n=>`<input data-k="${n}" placeholder="${n}">`).join("");$("#run").innerHTML=`<div class="hero"><p class="sub">${r.t} · ${i+1}/${steps.length}</p><h2>${titel}</h2></div>${names||""}<p class="words">${fill(text,mem)}</p>${last?`<label class="check"><input type="checkbox" id="back"><span>Ich kehre zurück.</span></label>`:""}<div class="row"><button type="button" class="btn ghost" id="prev">${i?"Zurück":"Wahl"}</button><button type="button" class="btn primary" id="next">${last?"So sei es":"Weiter"}</button></div><p class="msg" id="msg"></p>`;$$("#run [data-k]").forEach(inp=>inp.oninput=()=>{mem[inp.dataset.k]=inp.value.trim()});$("#prev").onclick=()=>{if(!i){gate();return}i--;draw()};$("#next").onclick=()=>{if(i<steps.length-1){i++;draw();return}if(!$("#back")||!$("#back").checked){$("#msg").textContent="Erst zurückkehren.";return}const d=load();d.log.unshift({id:uid(),t:now(),titel:r.t,wer:[mem.Name,mem.A,mem.B].filter(Boolean).join(" · "),wesen:!!mit});if(fromPlan){d.planned=d.planned.filter(p=>p.pid!==fromPlan);fromPlan=null}save(d);show("after")}};
show("run");gate()}
function renderList(){const order=["Alltag","Schutz","Energie","Liebe","Trennung","Feld"];$("#cats").innerHTML=["Alle",...order].map(x=>`<button class="chip${x===cat?" on":""}" data-cat="${x}">${x}</button>`).join("");$$("#cats [data-cat]").forEach(b=>b.onclick=()=>{cat=b.dataset.cat;renderList()});const items=R.filter(r=>cat==="Alle"||r.tag===cat);const g={};items.forEach(r=>{(g[r.tag]=g[r.tag]||[]).push(r)});$("#list").innerHTML=Object.keys(g).sort((a,b)=>order.indexOf(a)-order.indexOf(b)).map(k=>`<p class="group">${k}</p>`+g[k].map(r=>`<button class="card" data-id="${r.id}"><b>${r.t}</b><small>${r.s}</small></button>`).join("")).join("");$$("#list .card").forEach(b=>b.onclick=()=>{fromPlan=null;openR(b.dataset.id)})}
function paintPlan(){const d=load(),sel=$("#plR");if(sel&&sel.options.length!==R.length){sel.innerHTML="";R.forEach(r=>{const o=document.createElement("option");o.value=r.id;o.textContent=r.t;sel.appendChild(o)})}$("#plList").innerHTML=d.planned.length?d.planned.map(x=>`<div class="entry"><b>${esc(x.titel)}</b><div class="meta">${esc(x.wer||"")}</div><button class="btn primary" data-go="${x.pid}">Setzen</button></div>`).join(""):"<p class='sub'>Nichts geplant.</p>";$$("#plList [data-go]").forEach(b=>b.onclick=()=>{const x=load().planned.find(p=>p.pid===b.dataset.go);if(x){fromPlan=x.pid;openR(x.id,x.wer)}})}
function paintNotes(){const notes=loadNotes();$("#notesOnly").innerHTML=notes.length?notes.map(n=>`<div class="entry"><div class="meta">${esc(n.t)}</div><p>${esc(n.note)}</p></div>`).join(""):"<p class='sub'>Keine Notiz.</p>"}
function paintLog(){const rows=load().log||[];$("#entries").innerHTML=rows.length?rows.map(e=>`<div class="entry"><b>${esc(e.titel)}</b><div class="meta">${esc(e.t)} ${esc(e.wer||"")}</div></div>`).join(""):"<p class='sub'>Noch leer.</p>"}
async function paintBuch(){
  const page=$("#page"); if(!page) return;
  page.innerHTML="<p class='sub'>Buch lädt …</p>";
  if(!BOOKTEXT){
    try{
      const parts=await Promise.all([0,1,2,3,4].map(n=>fetch("pdfpart"+n+".txt",{cache:"reload"}).then(r=>{if(!r.ok)throw new Error(n);return r.text()})));
      BOOKTEXT=parts.join("\n\n");
    }catch(e){
      page.innerHTML="<p class='sub'>Buchdateien kommen. Neu laden.</p>";
      return;
    }
  }
  page.innerHTML="";
  const pre=document.createElement("div");
  pre.style.whiteSpace="pre-wrap";
  pre.style.fontFamily="Georgia,serif";
  pre.style.lineHeight="1.65";
  pre.style.fontSize="1.02rem";
  pre.textContent=BOOKTEXT;
  page.appendChild(pre);
}
document.addEventListener("click",e=>{const n=e.target.closest("nav button");if(n)show(n.dataset.v)});
$("#plAdd").onclick=()=>{const r=R.find(x=>x.id===$("#plR").value);if(!r)return;const d=load();d.planned.unshift({pid:uid(),id:r.id,titel:r.t,wer:($("#plW").value||"").trim(),t:now()});save(d);paintPlan()};
$("#noteAdd").onclick=()=>{const tx=($("#noteT").value||"").trim();if(!tx)return;const n=loadNotes();n.unshift({id:uid(),t:now(),note:tx});saveNotes(n);$("#noteT").value="";paintNotes()};
$("#quick").onclick=()=>{const d=load();d.log.unshift({id:uid(),t:now(),titel:"Feld zu"});save(d);show("after")};
$("#afterStay").onclick=()=>show("home");$("#afterGo").onclick=()=>show("bye");$("#stay").onclick=()=>show("home");
renderList();
